name: lucky_navigation_bar
description: iOS 26 inspired navigation bar
version: 1.0.0
homepage: https://github.com/jesusrp98/lucky_navigation_bar

environment:
  flutter: '>=3.38.0 <4.0.0'
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  motor: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
