name: lucky_navigation_bar
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  motor: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
